package com.web.note.dao;

import com.web.note.entity.FileType;
import com.web.note.entity.FileTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int countByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int deleteByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int insert(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int insertSelective(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    List<FileType> selectByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    FileType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int updateByExampleSelective(@Param("record") FileType record, @Param("example") FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int updateByExample(@Param("record") FileType record, @Param("example") FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int updateByPrimaryKeySelective(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    int updateByPrimaryKey(FileType record);
}