package com.web.note.dao;

import com.web.note.entity.Image;
import com.web.note.entity.ImageExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int countByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int deleteByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int deleteByPrimaryKey(String imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int insertSelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    List<Image> selectByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    Image selectByPrimaryKey(String imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int updateByExampleSelective(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int updateByExample(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int updateByPrimaryKeySelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Mon Feb 10 14:57:59 CST 2025
     */
    int updateByPrimaryKey(Image record);


    int getSumSizeInCollection(String collectionId);

    int countInCollection(String collectionId);

    int getSumSizeInDocument(String documentId);

    int countInDocument(String documentId);

    List<Image> getImagesByUserIdHavingImage(String userId, String documentId);

    int countImageSizeByUser(@Param("userId") String userId);

    List<Image> getAllInvalidImage(Map<String, Object> params);

    // Method for batch deleting images based on a list of image IDs
    void batchDelete(Map<String, Object> params);
}