package com.web.note.dao;

import com.web.note.entity.IpBan;
import com.web.note.entity.IpBanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IpBanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int countByExample(IpBanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int deleteByExample(IpBanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int deleteByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int insert(IpBan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int insertSelective(IpBan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    List<IpBan> selectByExample(IpBanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    IpBan selectByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int updateByExampleSelective(@Param("record") IpBan record, @Param("example") IpBanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int updateByExample(@Param("record") IpBan record, @Param("example") IpBanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int updateByPrimaryKeySelective(IpBan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_ban
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    int updateByPrimaryKey(IpBan record);
}