package com.web.note.entity;

import java.util.ArrayList;
import java.util.List;

public class AppConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public AppConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConfigItemIsNull() {
            addCriterion("config_item is null");
            return (Criteria) this;
        }

        public Criteria andConfigItemIsNotNull() {
            addCriterion("config_item is not null");
            return (Criteria) this;
        }

        public Criteria andConfigItemEqualTo(String value) {
            addCriterion("config_item =", value, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemNotEqualTo(String value) {
            addCriterion("config_item <>", value, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemGreaterThan(String value) {
            addCriterion("config_item >", value, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemGreaterThanOrEqualTo(String value) {
            addCriterion("config_item >=", value, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemLessThan(String value) {
            addCriterion("config_item <", value, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemLessThanOrEqualTo(String value) {
            addCriterion("config_item <=", value, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemLike(String value) {
            addCriterion("config_item like", value, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemNotLike(String value) {
            addCriterion("config_item not like", value, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemIn(List<String> values) {
            addCriterion("config_item in", values, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemNotIn(List<String> values) {
            addCriterion("config_item not in", values, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemBetween(String value1, String value2) {
            addCriterion("config_item between", value1, value2, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigItemNotBetween(String value1, String value2) {
            addCriterion("config_item not between", value1, value2, "configItem");
            return (Criteria) this;
        }

        public Criteria andConfigNameIsNull() {
            addCriterion("config_name is null");
            return (Criteria) this;
        }

        public Criteria andConfigNameIsNotNull() {
            addCriterion("config_name is not null");
            return (Criteria) this;
        }

        public Criteria andConfigNameEqualTo(String value) {
            addCriterion("config_name =", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotEqualTo(String value) {
            addCriterion("config_name <>", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameGreaterThan(String value) {
            addCriterion("config_name >", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameGreaterThanOrEqualTo(String value) {
            addCriterion("config_name >=", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLessThan(String value) {
            addCriterion("config_name <", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLessThanOrEqualTo(String value) {
            addCriterion("config_name <=", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLike(String value) {
            addCriterion("config_name like", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotLike(String value) {
            addCriterion("config_name not like", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameIn(List<String> values) {
            addCriterion("config_name in", values, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotIn(List<String> values) {
            addCriterion("config_name not in", values, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameBetween(String value1, String value2) {
            addCriterion("config_name between", value1, value2, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotBetween(String value1, String value2) {
            addCriterion("config_name not between", value1, value2, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigValueIsNull() {
            addCriterion("config_value is null");
            return (Criteria) this;
        }

        public Criteria andConfigValueIsNotNull() {
            addCriterion("config_value is not null");
            return (Criteria) this;
        }

        public Criteria andConfigValueEqualTo(String value) {
            addCriterion("config_value =", value, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueNotEqualTo(String value) {
            addCriterion("config_value <>", value, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueGreaterThan(String value) {
            addCriterion("config_value >", value, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueGreaterThanOrEqualTo(String value) {
            addCriterion("config_value >=", value, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueLessThan(String value) {
            addCriterion("config_value <", value, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueLessThanOrEqualTo(String value) {
            addCriterion("config_value <=", value, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueLike(String value) {
            addCriterion("config_value like", value, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueNotLike(String value) {
            addCriterion("config_value not like", value, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueIn(List<String> values) {
            addCriterion("config_value in", values, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueNotIn(List<String> values) {
            addCriterion("config_value not in", values, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueBetween(String value1, String value2) {
            addCriterion("config_value between", value1, value2, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigValueNotBetween(String value1, String value2) {
            addCriterion("config_value not between", value1, value2, "configValue");
            return (Criteria) this;
        }

        public Criteria andConfigRangeIsNull() {
            addCriterion("config_range is null");
            return (Criteria) this;
        }

        public Criteria andConfigRangeIsNotNull() {
            addCriterion("config_range is not null");
            return (Criteria) this;
        }

        public Criteria andConfigRangeEqualTo(String value) {
            addCriterion("config_range =", value, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeNotEqualTo(String value) {
            addCriterion("config_range <>", value, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeGreaterThan(String value) {
            addCriterion("config_range >", value, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeGreaterThanOrEqualTo(String value) {
            addCriterion("config_range >=", value, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeLessThan(String value) {
            addCriterion("config_range <", value, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeLessThanOrEqualTo(String value) {
            addCriterion("config_range <=", value, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeLike(String value) {
            addCriterion("config_range like", value, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeNotLike(String value) {
            addCriterion("config_range not like", value, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeIn(List<String> values) {
            addCriterion("config_range in", values, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeNotIn(List<String> values) {
            addCriterion("config_range not in", values, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeBetween(String value1, String value2) {
            addCriterion("config_range between", value1, value2, "configRange");
            return (Criteria) this;
        }

        public Criteria andConfigRangeNotBetween(String value1, String value2) {
            addCriterion("config_range not between", value1, value2, "configRange");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_config
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 16 21:35:43 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_config
     *
     * @mbggenerated Thu Nov 16 21:35:43 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}