package com.web.note.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApplicationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public ApplicationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdIsNull() {
            addCriterion("app_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAppUserIdIsNotNull() {
            addCriterion("app_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppUserIdEqualTo(String value) {
            addCriterion("app_user_id =", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdNotEqualTo(String value) {
            addCriterion("app_user_id <>", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdGreaterThan(String value) {
            addCriterion("app_user_id >", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_user_id >=", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdLessThan(String value) {
            addCriterion("app_user_id <", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdLessThanOrEqualTo(String value) {
            addCriterion("app_user_id <=", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdLike(String value) {
            addCriterion("app_user_id like", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdNotLike(String value) {
            addCriterion("app_user_id not like", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdIn(List<String> values) {
            addCriterion("app_user_id in", values, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdNotIn(List<String> values) {
            addCriterion("app_user_id not in", values, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdBetween(String value1, String value2) {
            addCriterion("app_user_id between", value1, value2, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdNotBetween(String value1, String value2) {
            addCriterion("app_user_id not between", value1, value2, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppTypeIsNull() {
            addCriterion("app_type is null");
            return (Criteria) this;
        }

        public Criteria andAppTypeIsNotNull() {
            addCriterion("app_type is not null");
            return (Criteria) this;
        }

        public Criteria andAppTypeEqualTo(String value) {
            addCriterion("app_type =", value, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeNotEqualTo(String value) {
            addCriterion("app_type <>", value, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeGreaterThan(String value) {
            addCriterion("app_type >", value, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeGreaterThanOrEqualTo(String value) {
            addCriterion("app_type >=", value, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeLessThan(String value) {
            addCriterion("app_type <", value, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeLessThanOrEqualTo(String value) {
            addCriterion("app_type <=", value, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeLike(String value) {
            addCriterion("app_type like", value, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeNotLike(String value) {
            addCriterion("app_type not like", value, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeIn(List<String> values) {
            addCriterion("app_type in", values, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeNotIn(List<String> values) {
            addCriterion("app_type not in", values, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeBetween(String value1, String value2) {
            addCriterion("app_type between", value1, value2, "appType");
            return (Criteria) this;
        }

        public Criteria andAppTypeNotBetween(String value1, String value2) {
            addCriterion("app_type not between", value1, value2, "appType");
            return (Criteria) this;
        }

        public Criteria andAppValueIsNull() {
            addCriterion("app_value is null");
            return (Criteria) this;
        }

        public Criteria andAppValueIsNotNull() {
            addCriterion("app_value is not null");
            return (Criteria) this;
        }

        public Criteria andAppValueEqualTo(String value) {
            addCriterion("app_value =", value, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueNotEqualTo(String value) {
            addCriterion("app_value <>", value, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueGreaterThan(String value) {
            addCriterion("app_value >", value, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueGreaterThanOrEqualTo(String value) {
            addCriterion("app_value >=", value, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueLessThan(String value) {
            addCriterion("app_value <", value, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueLessThanOrEqualTo(String value) {
            addCriterion("app_value <=", value, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueLike(String value) {
            addCriterion("app_value like", value, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueNotLike(String value) {
            addCriterion("app_value not like", value, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueIn(List<String> values) {
            addCriterion("app_value in", values, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueNotIn(List<String> values) {
            addCriterion("app_value not in", values, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueBetween(String value1, String value2) {
            addCriterion("app_value between", value1, value2, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppValueNotBetween(String value1, String value2) {
            addCriterion("app_value not between", value1, value2, "appValue");
            return (Criteria) this;
        }

        public Criteria andAppContentIsNull() {
            addCriterion("app_content is null");
            return (Criteria) this;
        }

        public Criteria andAppContentIsNotNull() {
            addCriterion("app_content is not null");
            return (Criteria) this;
        }

        public Criteria andAppContentEqualTo(String value) {
            addCriterion("app_content =", value, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentNotEqualTo(String value) {
            addCriterion("app_content <>", value, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentGreaterThan(String value) {
            addCriterion("app_content >", value, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentGreaterThanOrEqualTo(String value) {
            addCriterion("app_content >=", value, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentLessThan(String value) {
            addCriterion("app_content <", value, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentLessThanOrEqualTo(String value) {
            addCriterion("app_content <=", value, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentLike(String value) {
            addCriterion("app_content like", value, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentNotLike(String value) {
            addCriterion("app_content not like", value, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentIn(List<String> values) {
            addCriterion("app_content in", values, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentNotIn(List<String> values) {
            addCriterion("app_content not in", values, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentBetween(String value1, String value2) {
            addCriterion("app_content between", value1, value2, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppContentNotBetween(String value1, String value2) {
            addCriterion("app_content not between", value1, value2, "appContent");
            return (Criteria) this;
        }

        public Criteria andAppStatusIsNull() {
            addCriterion("app_status is null");
            return (Criteria) this;
        }

        public Criteria andAppStatusIsNotNull() {
            addCriterion("app_status is not null");
            return (Criteria) this;
        }

        public Criteria andAppStatusEqualTo(Integer value) {
            addCriterion("app_status =", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotEqualTo(Integer value) {
            addCriterion("app_status <>", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusGreaterThan(Integer value) {
            addCriterion("app_status >", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("app_status >=", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusLessThan(Integer value) {
            addCriterion("app_status <", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusLessThanOrEqualTo(Integer value) {
            addCriterion("app_status <=", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusIn(List<Integer> values) {
            addCriterion("app_status in", values, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotIn(List<Integer> values) {
            addCriterion("app_status not in", values, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusBetween(Integer value1, Integer value2) {
            addCriterion("app_status between", value1, value2, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("app_status not between", value1, value2, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateIsNull() {
            addCriterion("app_submit_date is null");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateIsNotNull() {
            addCriterion("app_submit_date is not null");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateEqualTo(Date value) {
            addCriterion("app_submit_date =", value, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateNotEqualTo(Date value) {
            addCriterion("app_submit_date <>", value, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateGreaterThan(Date value) {
            addCriterion("app_submit_date >", value, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateGreaterThanOrEqualTo(Date value) {
            addCriterion("app_submit_date >=", value, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateLessThan(Date value) {
            addCriterion("app_submit_date <", value, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateLessThanOrEqualTo(Date value) {
            addCriterion("app_submit_date <=", value, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateIn(List<Date> values) {
            addCriterion("app_submit_date in", values, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateNotIn(List<Date> values) {
            addCriterion("app_submit_date not in", values, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateBetween(Date value1, Date value2) {
            addCriterion("app_submit_date between", value1, value2, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppSubmitDateNotBetween(Date value1, Date value2) {
            addCriterion("app_submit_date not between", value1, value2, "appSubmitDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateIsNull() {
            addCriterion("app_deal_date is null");
            return (Criteria) this;
        }

        public Criteria andAppDealDateIsNotNull() {
            addCriterion("app_deal_date is not null");
            return (Criteria) this;
        }

        public Criteria andAppDealDateEqualTo(Date value) {
            addCriterion("app_deal_date =", value, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateNotEqualTo(Date value) {
            addCriterion("app_deal_date <>", value, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateGreaterThan(Date value) {
            addCriterion("app_deal_date >", value, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateGreaterThanOrEqualTo(Date value) {
            addCriterion("app_deal_date >=", value, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateLessThan(Date value) {
            addCriterion("app_deal_date <", value, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateLessThanOrEqualTo(Date value) {
            addCriterion("app_deal_date <=", value, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateIn(List<Date> values) {
            addCriterion("app_deal_date in", values, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateNotIn(List<Date> values) {
            addCriterion("app_deal_date not in", values, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateBetween(Date value1, Date value2) {
            addCriterion("app_deal_date between", value1, value2, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealDateNotBetween(Date value1, Date value2) {
            addCriterion("app_deal_date not between", value1, value2, "appDealDate");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdIsNull() {
            addCriterion("app_deal_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdIsNotNull() {
            addCriterion("app_deal_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdEqualTo(String value) {
            addCriterion("app_deal_user_id =", value, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdNotEqualTo(String value) {
            addCriterion("app_deal_user_id <>", value, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdGreaterThan(String value) {
            addCriterion("app_deal_user_id >", value, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_deal_user_id >=", value, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdLessThan(String value) {
            addCriterion("app_deal_user_id <", value, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdLessThanOrEqualTo(String value) {
            addCriterion("app_deal_user_id <=", value, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdLike(String value) {
            addCriterion("app_deal_user_id like", value, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdNotLike(String value) {
            addCriterion("app_deal_user_id not like", value, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdIn(List<String> values) {
            addCriterion("app_deal_user_id in", values, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdNotIn(List<String> values) {
            addCriterion("app_deal_user_id not in", values, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdBetween(String value1, String value2) {
            addCriterion("app_deal_user_id between", value1, value2, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserIdNotBetween(String value1, String value2) {
            addCriterion("app_deal_user_id not between", value1, value2, "appDealUserId");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameIsNull() {
            addCriterion("app_deal_user_name is null");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameIsNotNull() {
            addCriterion("app_deal_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameEqualTo(String value) {
            addCriterion("app_deal_user_name =", value, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameNotEqualTo(String value) {
            addCriterion("app_deal_user_name <>", value, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameGreaterThan(String value) {
            addCriterion("app_deal_user_name >", value, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_deal_user_name >=", value, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameLessThan(String value) {
            addCriterion("app_deal_user_name <", value, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameLessThanOrEqualTo(String value) {
            addCriterion("app_deal_user_name <=", value, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameLike(String value) {
            addCriterion("app_deal_user_name like", value, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameNotLike(String value) {
            addCriterion("app_deal_user_name not like", value, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameIn(List<String> values) {
            addCriterion("app_deal_user_name in", values, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameNotIn(List<String> values) {
            addCriterion("app_deal_user_name not in", values, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameBetween(String value1, String value2) {
            addCriterion("app_deal_user_name between", value1, value2, "appDealUserName");
            return (Criteria) this;
        }

        public Criteria andAppDealUserNameNotBetween(String value1, String value2) {
            addCriterion("app_deal_user_name not between", value1, value2, "appDealUserName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 23 18:19:00 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application
     *
     * @mbggenerated Thu Nov 23 18:19:00 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}