package com.web.note.entity;

import java.util.ArrayList;
import java.util.List;

public class FileTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public FileTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnIsNull() {
            addCriterion("type_name_en is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnIsNotNull() {
            addCriterion("type_name_en is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnEqualTo(String value) {
            addCriterion("type_name_en =", value, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnNotEqualTo(String value) {
            addCriterion("type_name_en <>", value, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnGreaterThan(String value) {
            addCriterion("type_name_en >", value, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("type_name_en >=", value, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnLessThan(String value) {
            addCriterion("type_name_en <", value, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnLessThanOrEqualTo(String value) {
            addCriterion("type_name_en <=", value, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnLike(String value) {
            addCriterion("type_name_en like", value, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnNotLike(String value) {
            addCriterion("type_name_en not like", value, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnIn(List<String> values) {
            addCriterion("type_name_en in", values, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnNotIn(List<String> values) {
            addCriterion("type_name_en not in", values, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnBetween(String value1, String value2) {
            addCriterion("type_name_en between", value1, value2, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameEnNotBetween(String value1, String value2) {
            addCriterion("type_name_en not between", value1, value2, "typeNameEn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnIsNull() {
            addCriterion("type_name_cn is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnIsNotNull() {
            addCriterion("type_name_cn is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnEqualTo(String value) {
            addCriterion("type_name_cn =", value, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnNotEqualTo(String value) {
            addCriterion("type_name_cn <>", value, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnGreaterThan(String value) {
            addCriterion("type_name_cn >", value, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnGreaterThanOrEqualTo(String value) {
            addCriterion("type_name_cn >=", value, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnLessThan(String value) {
            addCriterion("type_name_cn <", value, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnLessThanOrEqualTo(String value) {
            addCriterion("type_name_cn <=", value, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnLike(String value) {
            addCriterion("type_name_cn like", value, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnNotLike(String value) {
            addCriterion("type_name_cn not like", value, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnIn(List<String> values) {
            addCriterion("type_name_cn in", values, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnNotIn(List<String> values) {
            addCriterion("type_name_cn not in", values, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnBetween(String value1, String value2) {
            addCriterion("type_name_cn between", value1, value2, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeNameCnNotBetween(String value1, String value2) {
            addCriterion("type_name_cn not between", value1, value2, "typeNameCn");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNull() {
            addCriterion("content_type is null");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNotNull() {
            addCriterion("content_type is not null");
            return (Criteria) this;
        }

        public Criteria andContentTypeEqualTo(String value) {
            addCriterion("content_type =", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotEqualTo(String value) {
            addCriterion("content_type <>", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThan(String value) {
            addCriterion("content_type >", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("content_type >=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThan(String value) {
            addCriterion("content_type <", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThanOrEqualTo(String value) {
            addCriterion("content_type <=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLike(String value) {
            addCriterion("content_type like", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotLike(String value) {
            addCriterion("content_type not like", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeIn(List<String> values) {
            addCriterion("content_type in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotIn(List<String> values) {
            addCriterion("content_type not in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeBetween(String value1, String value2) {
            addCriterion("content_type between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotBetween(String value1, String value2) {
            addCriterion("content_type not between", value1, value2, "contentType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_type
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 03 09:43:13 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}