package com.web.note.entity;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class FileType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type.id
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type.type_name_en
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    private String typeNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type.type_name_cn
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    private String typeNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type.content_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    private String contentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type.id
     *
     * @return the value of file_type.id
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type.id
     *
     * @param id the value for file_type.id
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type.type_name_en
     *
     * @return the value of file_type.type_name_en
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public String getTypeNameEn() {
        return typeNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type.type_name_en
     *
     * @param typeNameEn the value for file_type.type_name_en
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public void setTypeNameEn(String typeNameEn) {
        this.typeNameEn = typeNameEn == null ? null : typeNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type.type_name_cn
     *
     * @return the value of file_type.type_name_cn
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public String getTypeNameCn() {
        return typeNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type.type_name_cn
     *
     * @param typeNameCn the value for file_type.type_name_cn
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public void setTypeNameCn(String typeNameCn) {
        this.typeNameCn = typeNameCn == null ? null : typeNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type.content_type
     *
     * @return the value of file_type.content_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type.content_type
     *
     * @param contentType the value for file_type.content_type
     *
     * @mbggenerated Tue Dec 03 09:43:13 CST 2024
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }
}