package com.web.note.entity;

import java.util.Date;

public class IpBan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_ban.ip
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_ban.ban_type
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    private Integer banType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_ban.start_time
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_ban.end_time
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_ban.reason
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_ban.created_at
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_ban.ip
     *
     * @return the value of ip_ban.ip
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_ban.ip
     *
     * @param ip the value for ip_ban.ip
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_ban.ban_type
     *
     * @return the value of ip_ban.ban_type
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public Integer getBanType() {
        return banType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_ban.ban_type
     *
     * @param banType the value for ip_ban.ban_type
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public void setBanType(Integer banType) {
        this.banType = banType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_ban.start_time
     *
     * @return the value of ip_ban.start_time
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_ban.start_time
     *
     * @param startTime the value for ip_ban.start_time
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_ban.end_time
     *
     * @return the value of ip_ban.end_time
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_ban.end_time
     *
     * @param endTime the value for ip_ban.end_time
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_ban.reason
     *
     * @return the value of ip_ban.reason
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_ban.reason
     *
     * @param reason the value for ip_ban.reason
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_ban.created_at
     *
     * @return the value of ip_ban.created_at
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_ban.created_at
     *
     * @param createdAt the value for ip_ban.created_at
     *
     * @mbggenerated Fri Nov 08 10:39:58 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}