package com.web.note.entity;

import java.util.Date;

public class UserSession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.session_id
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.user_id
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.create_date
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.expiry_date
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.create_info
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    private String createInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.session_id
     *
     * @return the value of session.session_id
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.session_id
     *
     * @param sessionId the value for session.session_id
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.user_id
     *
     * @return the value of session.user_id
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.user_id
     *
     * @param userId the value for session.user_id
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.create_date
     *
     * @return the value of session.create_date
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.create_date
     *
     * @param createDate the value for session.create_date
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.expiry_date
     *
     * @return the value of session.expiry_date
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.expiry_date
     *
     * @param expiryDate the value for session.expiry_date
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.create_info
     *
     * @return the value of session.create_info
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public String getCreateInfo() {
        return createInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.create_info
     *
     * @param createInfo the value for session.create_info
     *
     * @mbggenerated Thu Apr 18 19:27:16 CST 2024
     */
    public void setCreateInfo(String createInfo) {
        this.createInfo = createInfo == null ? null : createInfo.trim();
    }
}